## Sections:  
- DataFrames  
- Data Exploration
- Effective Health

In [1]:
import pandas as pd
import numpy as np
import league_stats as lol

# DataFrames
Pandas DataFrames are tabular data structures used to organize and manipulate data; 
in this case the data being champion and item statistics.

For the champions DataFrame, each column represents an attribute describing either:   
the champion's attribute value at level 1; or the growth rate of the attribute per level (columns ending in "+").

In [2]:
champs_df = lol.champions_df()
champs_df.head()

,HP,HP+,HP5,HP5+,MP,MP+,MP5,MP5+,AD,AD+,AS,AS+,AR,AR+,MR,MR+,MS,Range
Champion,,,,,,,,,,,,,,,,,,
Aatrox,537.80,85.0,6.590,0.50,30.00,45.0,0.00,0.000,60.3760,3.20,0.651,0.03000,24.384,3.8,32.1,1.25,345.0,150.0
Ahri,514.40,80.0,6.505,0.60,334.00,50.0,6.00,0.800,53.0400,3.00,0.668,0.02000,20.880,3.5,30.0,0.00,330.0,550.0
Akali,587.80,85.0,8.340,0.65,200.00,0.0,50.00,0.000,58.3760,3.20,0.694,0.03100,26.380,3.5,32.1,1.25,350.0,125.0
Alistar,613.36,106.0,8.675,0.85,278.84,38.0,8.50,0.800,61.1116,3.62,0.625,0.02125,24.380,3.5,32.1,1.25,330.0,125.0
Amumu,613.12,84.0,8.875,0.85,287.20,40.0,7.38,0.525,53.3840,3.80,0.638,0.02180,23.544,3.8,32.1,1.25,335.0,125.0

The items DataFrame contains the values for an item's non-unique attributes. 
A NaN value means the item lacks that particular attribute.

In [87]:
items_df = lol.items_df()
items_df.head()

,AD,AP,AS,AR,CDR,Cost,Crit,HP5,HP,Lifesteal,MP5,MR,Mana
Item,,,,,,,,,,,,,
Abyssal Scepter,NaN,60.0,NaN,NaN,0.10,2750.0,NaN,NaN,NaN,NaN,NaN,60.0,NaN
Aegis of the Legion,NaN,NaN,NaN,NaN,NaN,1500.0,NaN,1.0,200.0,NaN,NaN,20.0,NaN
Aether Wisp,NaN,30.0,NaN,NaN,NaN,850.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amplifying Tome,NaN,20.0,NaN,NaN,NaN,435.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ancient Coin,NaN,NaN,NaN,NaN,0.05,350.0,NaN,NaN,NaN,NaN,0.25,NaN,NaN

The champions DataFrame can be used to construct another DataFrame containing a specified champion's  
growth stats for each individual level 1-18, inclusive:

In [241]:
growth_df = lol.champ_growth_df('Fiddlesticks')
growth_df

           HP     HP5       MP      AD      AS     AR    MR
Level
1       524.4   5.605   400.12  48.360  0.6250  20.88  30.0
2       604.4   6.205   456.12  50.985  0.6461  24.38  30.0
3       684.4   6.805   512.12  53.610  0.6672  27.88  30.0
4       764.4   7.405   568.12  56.235  0.6883  31.38  30.0
5       844.4   8.005   624.12  58.860  0.7094  34.88  30.0
6       924.4   8.605   680.12  61.485  0.7305  38.38  30.0
7      1004.4   9.205   736.12  64.110  0.7516  41.88  30.0
8      1084.4   9.805   792.12  66.735  0.7727  45.38  30.0
9      1164.4  10.405   848.12  69.360  0.7938  48.88  30.0
10     1244.4  11.005   904.12  71.985  0.8149  52.38  30.0
11     1324.4  11.605   960.12  74.610  0.8360  55.88  30.0
12     1404.4  12.205  1016.12  77.235  0.8571  59.38  30.0
13     1484.4  12.805  1072.12  79.860  0.8782  62.88  30.0
14     1564.4  13.405  1128.12  82.485  0.8993  66.38  30.0
15     1644.4  14.005  1184.12  85.110  0.9204  69.88  30.0
16     1724.4  14.605  1240.12  87.735  0.9415  73.38  30.0
17     1804.4  15.205  1296.12  90.360  0.9626  76.88  30.0
18     1884.4  15.805  1352.12  92.985  0.9837  80.38  30.0

# Data Exploration

The above DataFrames contain easily accessible data that can be further manipulated to provide interesting insights.

Display champions whose names begin with 'M':

In [11]:
champs_df.loc['M':'N']

,HP,HP+,HP5,HP5+,MP,MP+,MP5,MP5+,AD,AD+,AS,AS+,AR,AR+,MR,MR+,MS,Range
Champion,,,,,,,,,,,,,,,,,,
Malphite,574.20,90.0,7.000,0.55,282.20,40.0,7.320,0.55,61.970,3.375,0.638,0.03400,28.300,3.75,32.1,1.25,335.0,125.0
Malzahar,514.40,80.0,5.420,0.55,325.60,45.0,6.000,0.80,54.700,3.000,0.625,0.01360,21.880,3.50,30.0,0.00,340.0,550.0
Maokai,572.20,90.0,7.000,0.75,377.28,43.0,7.205,0.45,63.544,3.300,0.694,0.02125,28.720,4.00,32.0,1.25,335.0,125.0
Master Yi,598.56,92.0,7.590,0.65,250.56,42.0,7.255,0.45,60.040,3.000,0.679,0.02000,24.040,3.00,32.1,1.25,355.0,125.0
Miss Fortune,530.00,85.0,6.190,0.65,325.84,35.0,8.040,0.65,46.000,1.000,0.656,0.03000,24.040,3.00,30.0,0.00,325.0,550.0
Mordekaiser,525.00,73.0,4.000,0.30,120.00,0.0,0.000,0.00,61.000,5.000,0.601,0.02200,20.000,3.75,32.1,1.25,325.0,175.0
Morgana,547.48,86.0,5.705,0.60,340.80,60.0,8.500,0.80,55.460,3.500,0.625,0.01530,25.384,3.80,30.0,0.00,335.0,450.0

Return a comprehensive list of item names:

In [422]:
items_df.index[0:20].tolist()

['Abyssal Scepter',
 'Aegis of the Legion',
 'Aether Wisp',
 'Amplifying Tome',
 'Ancient Coin',
 'Arcane Sweeper',
 "Archangel's Staff",
 "Archangel's Staff (Crystal Scar)",
 'Ardent Censer',
 "Athene's Unholy Grail",
 'B. F. Sword',
 "Bami's Cinder",
 'Banner of Command',
 "Banshee's Veil",
 "Berserker's Greaves",
 'Bilgewater Cutlass',
 'Blade of the Ruined King',
 'Blasting Wand',
 'Bloodrazor',
 "Brawler's Gloves"]

Sort items by highest AD, and then by highest cost:

In [13]:
items_df.sort_values(by=['AD', 'Cost'], ascending=[0, 0])[0:10]

,AD,AP,AS,AR,CDR,Cost,Crit,HP5,HP,Lifesteal,MP5,MR,Mana
Item,,,,,,,,,,,,,
The Bloodthirster,75.0,NaN,NaN,NaN,NaN,3700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Death's Dance,75.0,NaN,NaN,NaN,0.1,3500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ravenous Hydra,75.0,NaN,NaN,NaN,NaN,3500,NaN,1.0,NaN,0.12,NaN,NaN,NaN
Duskblade of Draktharr,75.0,NaN,NaN,NaN,NaN,3250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Essence Reaver,70.0,NaN,NaN,NaN,NaN,3600,0.20,NaN,NaN,NaN,NaN,NaN,NaN
Infinity Edge,70.0,NaN,NaN,NaN,NaN,3600,0.20,NaN,NaN,NaN,NaN,NaN,NaN
Lord Van Damm's Pillager,65.0,NaN,NaN,NaN,NaN,3600,0.30,NaN,NaN,NaN,NaN,NaN,NaN
Mercurial Scimitar,65.0,NaN,NaN,NaN,NaN,3600,NaN,NaN,NaN,0.10,NaN,35.0,NaN
Mirage Blade,60.0,NaN,NaN,NaN,NaN,3200,0.15,NaN,NaN,0.12,NaN,NaN,NaN
Youmuu's Ghostblade,60.0,NaN,NaN,NaN,0.1,3200,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Display only those items with both HP and AP; sorted by highest AP value then highest HP value:

In [82]:
items_df[['AP', 'HP']][(items_df['HP'] > 0) & (items_df['AP'] > 0)].sort_values(by=['AP', 'HP'], ascending=[0, 0])

                               AP     HP
Item
Rylai's Crystal Scepter     100.0  400.0
Hextech GLP-800              80.0  300.0
Liandry's Torment            80.0  300.0
Trickster's Glass            60.0  400.0
Hextech Protobelt-01         60.0  300.0
Rod of Ages                  60.0  300.0
Rod of Ages (Crystal Scar)   60.0  300.0
Banner of Command            60.0  200.0
Guardian's Orb               30.0  150.0
Eye of the Watchers          25.0  200.0
Haunting Guise               25.0  200.0
Doran's Ring                 15.0   60.0

For each growth stat, return the mean rate of growth per level among all champions:

In [102]:
champs_df[['HP+', 'HP5+', 'MP+', 'AD+', 'AS+', 'AR+', 'MR+']].mean(axis=0)

HP+     84.246183
HP5+     0.650382
MP+     36.919847
AD+      3.134478
AS+      0.024046
AR+      3.464122
MR+      0.620229
dtype: float64

Find a champion's stats at a given level:

In [103]:
lol.champ_growth_df('Zyra').ix[12]

HP     1313.0000
HP5      11.1900
MP      884.0000
AD       88.5760
AS        0.8571
AR       53.0400
MR       30.0000
Name: 12, dtype: float64

Directly compares multiple specified champions and their base stat values:

In [109]:
champs_df.loc[['Fiddlesticks', 'Teemo', 'Zyra']]

,HP,HP+,HP5,HP5+,MP,MP+,MP5,MP5+,AD,AD+,AS,AS+,AR,AR+,MR,MR+,MS,Range
Champion,,,,,,,,,,,,,,,,,,
Fiddlesticks,524.40,80.0,5.605,0.60,400.12,56.0,6.000,0.80,48.360,2.625,0.625,0.0211,20.88,3.50,30.0,0.0,335.0,480.0
Teemo,515.76,82.0,5.740,0.65,267.20,40.0,7.205,0.45,49.540,3.000,0.690,0.0338,24.30,3.75,30.0,0.0,330.0,500.0
Zyra,499.00,74.0,5.690,0.50,334.00,50.0,8.500,0.80,53.376,3.200,0.625,0.0211,20.04,3.00,30.0,0.0,340.0,575.0

Create a MultiIndex DataFrame comparing multiple champion growth stat DataFrames:

In [323]:
df1 = lol.champ_growth_df('Fiddlesticks')
df2 = lol.champ_growth_df('Teemo')
df3 = lol.champ_growth_df('Zyra')
frames = {'Fiddlesticks': df1, 'Teemo': df2, 'Zyra': df3}
ftz_df = pd.concat(frames).swaplevel(i=-2, j=-1, axis=0).sortlevel(0)
ftz_df[0:9]

                        HP    HP5      MP      AD      AS     AR    MR
Level
1     Fiddlesticks  524.40  5.605  400.12  48.360  0.6250  20.88  30.0
      Teemo         515.76  5.740  267.20  49.540  0.6900  24.30  30.0
      Zyra          499.00  5.690  334.00  53.376  0.6250  20.04  30.0
2     Fiddlesticks  604.40  6.205  456.12  50.985  0.6461  24.38  30.0
      Teemo         597.76  6.390  307.20  52.540  0.7238  28.05  30.0
      Zyra          573.00  6.190  384.00  56.576  0.6461  23.04  30.0
3     Fiddlesticks  684.40  6.805  512.12  53.610  0.6672  27.88  30.0
      Teemo         679.76  7.040  347.20  55.540  0.7576  31.80  30.0
      Zyra          647.00  6.690  434.00  59.776  0.6672  26.04  30.0

# Effective Health

Effective health is an alternative method for calculating a champion's defensive stats that ignores the concept of damage reduction and instead applies armor and magic resistance to separate health pools. Essentially, assume the enemy physical or magic damage is applied similar to true damage; an attack that deals 100 physical damage would remove 100 health from a champion's physical effective health pool. The effective health pools themselves are calculated thus:  
    Physical Effective Health Pool (PEH) = [HP x (100 + AR) / 100]  
    Magical Effective Health Pool (MEH) = [HP x (100 +MR) / 100]  
  
Physical effective health can be interpreted as taking a champion's total health and increasing it by 1% for every point of armor the champion has. For example, a champion with 2,000 HP and 40 AR has [2,000 x (100 + 40)/100] = 2,800 PEH; again, this is simply increasing the 2,000 HP by 1% for every one of the 40 points of armor. So with 2,000 HP and 40 AR, an enemy champion that deals a consistent 100 physical damage with auto attacks will need to attack the above champion a total of 28 times before killing them (this is ignoring health regen, shields, etc…).

Given a specific champion, level, and item inventory- calculate a champion's displayed health, armor, and magic resistence, as well as their effective health against both physical damage and magical damage:

In [420]:
champ = 'Teemo'
level = 14
items = ['Abyssal Scepter', 'Frozen Heart', 'Spirit Visage']
s1 = pd.Series(lol.effective_health(champ, level, *items))
s2 = lol.leveled_with_items_stats(champ, level, *items)
eh_df = pd.DataFrame([s1, s2]).drop(['AD', 'AS', 'HP5'], axis=1)
eh_df

       AR       AR_EH       HP     MR     MR_EH
0     NaN  5476.06968  2081.76    NaN  5100.312
1  163.05         NaN  2081.76  145.0       NaN